version: "3.8"

services:
  httplistener:
    build:
      context: web
      dockerfile: Dockerfile
    restart: always
    privileged: false
    cap_drop:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FSETID
      - KILL
      - NET_BIND_SERVICE
      - NET_RAW
      - SETGID
      - SETUID
      - SYS_CHROOT
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://door:password@db_service/door
      - UPLOAD_FOLDER=/opt/web/uploads
      - LOG_FOLDER=/opt/web/logs
      - REVERSEPROXY=no
      - SECURE=no
      - TZ=Asia/Singapore
    working_dir: /opt/web
    volumes:
      - ./APPDATA/docker-${APP_NAME}/logs:/opt/web/logs:rw
      - ./APPDATA/docker-${APP_NAME}/uploads:/opt/web/uploads:rw
    depends_on:
      rabbit:
        condition: service_healthy
      db_service:
        condition: service_healthy
    networks:
      - external_net
      - internal_net

  telegram:
    build:
      context: telegram
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./APPDATA/docker-${APP_NAME}/uploads:/opt/telegram/uploads:ro
    depends_on:
      rabbit:
        condition: service_healthy
    networks:
      - external_net
      - internal_net

  rabbit:
    image: rabbitmq:3.8-management-alpine
    restart: always
    privileged: false
    cap_drop:
      - AUDIT_WRITE
      - DAC_OVERRIDE
      - KILL
      - NET_BIND_SERVICE
      - NET_RAW
      - SYS_CHROOT
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 3s
      timeout: 10s
      retries: 3
    networks:
      - internal_net
  
  db_service:
    image: postgres:alpine
    restart: always
    privileged: false
    cap_drop:
      - AUDIT_WRITE
      - KILL
      - NET_BIND_SERVICE
      - NET_RAW
    environment:
      - POSTGRES_USER=door
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=door
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./APPDATA/docker-${APP_NAME}/db:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      start_period: 10s
      interval: 10s
      timeout: 15s
      retries: 3
    networks:
      - internal_net

networks:
  external_net:
    driver: bridge
  internal_net:
    driver: bridge
    internal: true
